site_name: Steamdeck Docs
site_url: https://steamdeckdocs.org/
nav:
  - Home: index.md
  #- About: about.md
  - Applications:
    - Decky Loader: applications/deckyloader.md
    #- Emudeck: applications/emudeck.md
    #- Lutris: applications/lutris.md
  - Games:
    - 'TMNT: Shredders revenge': games/tmntshreddersrevenge.md
  - 'Non Steam Games':
    - 'Super Mario 64 decompiled': games/sm64.md
  - 'Tips & Tricks':
    - OBS: tipsandtricks/obs.md
    - SSH: tipsandtricks/ssh.md
    #- Streaming: tipsandtricks/streaming.md
repo_url: https://github.com/tuxx/steamdeckdocs
theme: 
  name: readthedocs
  logo: assets/logo.png
  favicon: assets/favicon.png
plugins:
  - search
  #- enumerate-headings:
  #    toc_depth: 0
  #    strict: true
  #    increment_across_pages: true
  #    include:
  #      - "*"
  #    exclude:
  #      - index.md
  #    restart_increment_after:
  #      - second_section.md
